### ISSUE TITLE
Fine-tune SAM for medical image segmentation

### ISSUE THREAD

**Issue by JunMa11** [JerryX1110/awesome-segment-anything-extensions#3]
We provide a step-by-step tutorial on fine-tuning SAM on 2D and 3D medical image datasets. It requires less than 10G GPU memory.
Hope that it could be useful.

https://github.com/bowang-lab/MedSAM#model-training-video-tutorial

**Comment by JerryX1110** [comment]
Thanks for your project! I have added it. : )
