### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by ldkong1205** [JerryX1110/awesome-segment-anything-extensions#4]
Thanks for meticulously maintaining this repository!

We would like to recommend our recent work on "Segment Any Point Cloud Sequences". 

We introduce **Seal**, a framework capable of leveraging 2D vision foundation models for self-supervised learning on large-scale 3D point clouds.

![Seal](https://github.com/youquanl/Segment-Any-Point-Cloud/raw/main/docs/figs/demo.gif)

- Paper: https://arxiv.org/abs/2306.09347
- Code: https://github.com/youquanl/Segment-Any-Point-Cloud
- Project Page: https://ldkong.com/Seal

Thanks a lot!

**Comment by JerryX1110** [comment]
Sorry for my late reply! 

Thanks for your project! The qualitative performance looks great on NuScenes dataset. I have added it. : )

**Comment by ldkong1205** [comment]
Thanks for your help!
